# http://www.invalidchecksum.net/2015/08/travis-ci-gce-docker-test-kitchen.html
language: ruby

bundler_args: --without local-integration

sudo: required

services:
  - docker

script:
  - bundle exec rake style
  - bundle exec rake unit
  - bundle exec kitchen test -d never

env:
  global:
    - KITCHEN_YAML=.kitchen.docker.yml
